# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-18 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adltrack', '0005_commit_username_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_version', models.CharField(max_length=32)),
                ('to_version', models.CharField(max_length=32)),
                ('backported', models.BooleanField()),
                ('commit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backport_record', to='adltrack.Commit')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together=set([('commit', 'from_version', 'to_version')]),
        ),
    ]
