# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-03 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32, unique=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            managers=[
                ('enabled_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CompilerHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('compiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory_app.Compiler')),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_version', models.PositiveIntegerField(choices=[(2009, 'gp2009'), (2016, 'gp2016')])),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('resource_revision', models.PositiveIntegerField()),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory_app.Procedure')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('export_sources', 'Export Sources'), ('compile', 'Compile'), ('compile_resources', 'Compile Resources')], max_length=32)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('completed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('output', models.TextField(blank=True)),
                ('compiler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='factory_app.Compiler')),
                ('procedure_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory_app.ProcedureRevision')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='procedure',
            unique_together=set([('schema_version', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([('name', 'procedure_revision', 'compiler')]),
        ),
        migrations.AlterUniqueTogether(
            name='procedurerevision',
            unique_together=set([('procedure', 'revision', 'resource_revision')]),
        ),
        migrations.AlterUniqueTogether(
            name='compilerhost',
            unique_together=set([('compiler', 'hostname')]),
        ),
    ]
