# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-03 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='key',
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([('key', 'procedure_revision', 'compiler')]),
        ),
    ]
