# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-03 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_app', '0004_auto_20170308_1027'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='compiler',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='key',
            field=models.CharField(choices=[('export_sources', 'Export Sources'), ('compile', 'Compile'), ('compile_resources', 'Compile Resources'), ('synchronize_legacy', 'Synchronize Legacy')], max_length=32),
        ),
    ]
