# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-07 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('factory_app', '0005_auto_20170403_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('procedure_revisions', models.ManyToManyField(related_name='batches', to='factory_app.ProcedureRevision')),
            ],
        ),
    ]
