# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-01-03 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_app', '0006_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='compiler',
            name='compatibility_version',
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
    ]
