# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-01-03 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('factory_app', '0007_compiler_compatibility_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompileLegacyTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('schema_version', models.PositiveIntegerField()),
                ('procedure_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=32)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=32)),
                ('output', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompileLegacyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
            ],
        ),
    ]
