# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-05-02 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('factory_app', '0008_compilelegacytask_compilelegacyuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='key',
            field=models.CharField(choices=[('export_sources', 'Export Sources'), ('compile', 'Compile'), ('compile_resources', 'Compile Resources'), ('synchronize_legacy', 'Synchronize Legacy'), ('technical_tests', 'Technical Tests')], max_length=32),
        ),
    ]
