# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-16 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InitialCommitRecord',
            fields=[
                ('adlobj_id', models.IntegerField(primary_key=True, serialize=False)),
                ('initial_commit', models.BooleanField()),
                ('version', models.IntegerField()),
                ('svndate', models.DateTimeField(blank=True, null=True)),
                ('user', models.CharField(blank=True, max_length=256, null=True)),
                ('revision', models.IntegerField(blank=True, null=True)),
                ('svn_path', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
