# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-13 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import neoxam.harry.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Push',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.CharField(max_length=255)),
                ('hostname', models.CharField(max_length=255)),
                ('session_id', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=neoxam.harry.models.untranslated_upload_to)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
