# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-28 12:42
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone
import neoxam.harry.models


class Migration(migrations.Migration):

    dependencies = [
        ('harry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonUntranslated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('comment', models.TextField()),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/workspace/src/neoxam/data/var/harry'), upload_to=neoxam.harry.models.json_upload_to)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
