# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-14 14:00
from __future__ import unicode_literals

import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('action', models.CharField(max_length=255)),
                ('schema_version', models.PositiveIntegerField()),
                ('procedure_name', models.CharField(max_length=255)),
                ('success', models.BooleanField()),
                ('data', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
    ]
