# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-31 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclipse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32)),
                ('enabled', models.BooleanField(default=False)),
                ('release_date', models.DateTimeField()),
            ],
        ),
    ]
