# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-09-03 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eclipse', '0002_runtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverTestTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('schema_version', models.PositiveIntegerField()),
                ('procedure_name', models.CharField(max_length=255)),
                ('procedure_test_name', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('compiling', 'Compiling'), ('success', 'Success'), ('failed', 'Failed')], default='compiling', max_length=32)),
                ('output', models.TextField(blank=True)),
            ],
        ),
    ]
