# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 11:10
from __future__ import unicode_literals

import _socket
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(default=_socket.gethostname, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True)),
                ('scm', models.CharField(choices=[('svn', 'Subversion')], default='svn', max_length=16)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together=set([('scm', 'url')]),
        ),
        migrations.AddField(
            model_name='checkout',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='scm.Repository'),
        ),
    ]
