# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
    ]
