# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0002_checkout_in_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='timeout',
            field=models.PositiveIntegerField(default=300),
            preserve_default=False,
        ),
    ]
