# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-28 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webintake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HttpServer',
            fields=[
                ('ip_address', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('port_number', models.IntegerField()),
            ],
        ),
    ]
