# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-04-18 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webintake', '0002_httpserver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HttpServer',
        ),
    ]
