# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(unique=True)),
                ('path', models.CharField(max_length=255)),
                ('data', jsonfield.fields.JSONField(default=dict)),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adltrack.Commit')),
            ],
            options={
                'get_latest_by': 'revision',
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(choices=[(710, 'gp710'), (2006, 'gp2006'), (2009, 'gp2009')])),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONField(default=dict)),
                ('head', models.BooleanField(default=True)),
                ('analyzed', models.BooleanField(default=True)),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_versions', to='adltrack.Commit')),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adltrack.ProcedureVersion')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_versions', to='adltrack.Procedure')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='procedure',
            unique_together=set([('version', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='procedureversion',
            unique_together=set([('procedure', 'commit')]),
        ),
    ]
