# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adltrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedureversion',
            name='magnum_compiled',
            field=models.BooleanField(default=False),
        ),
    ]
