# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('adltrack', '0002_procedureversion_magnum_compiled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='previous',
        ),
        migrations.RemoveField(
            model_name='procedureversion',
            name='previous',
        ),
    ]
