# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-04 13:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adltrack', '0003_auto_20160225_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='commit_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commit',
            name='username',
            field=models.CharField(default='hhu', max_length=255),
            preserve_default=False,
        ),
    ]
