# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-17 11:43
from __future__ import unicode_literals

import pytz
from django.db import migrations
from django.utils.timezone import utc

paris = pytz.timezone('Europe/Paris')


def complete_commits(apps, schema_editor):
    AdlObj = apps.get_model('versioning', 'AdlObj')
    Commit = apps.get_model('adltrack', 'Commit')
    for commit in Commit.objects.all():
        adl_obj = AdlObj.objects.get(revision=commit.revision)
        commit.username = adl_obj.user
        commit.commit_date = utc.normalize(paris.localize(adl_obj.svndate.replace(tzinfo=None)).astimezone(utc))
        commit.save(update_fields=('username', 'commit_date'))


class Migration(migrations.Migration):
    dependencies = [
        ('adltrack', '0004_auto_20161004_1357'),
        ('versioning', '0002_auto_20160226_0800'),
    ]

    operations = [
        migrations.RunPython(complete_commits),
    ]
