# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-21 11:20
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compilation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('compiling', 'Compiling'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('compiled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('output', models.TextField(blank=True)),
                ('src', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/workspace/src/sandbox/neoxam/neoxam/champagne'), upload_to='', verbose_name='Source')),
            ],
        ),
    ]
