# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-21 12:22
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champagne', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilation',
            name='procedure_name',
            field=models.CharField(default='migration', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compilation',
            name='src',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/workspace/src/neoxam/champagne'), upload_to='%Y/%m', verbose_name='Source'),
        ),
    ]
