# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-27 17:16
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champagne', '0002_auto_20170221_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilation',
            name='patterns',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='compilation',
            name='src',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/workspace/src/neoxam/data/var/champagne'), upload_to='%Y/%m', verbose_name='Source'),
        ),
    ]
