# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-03 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatchRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('version', models.CharField(max_length=32)),
                ('path', models.CharField(max_length=256)),
                ('status', models.BooleanField()),
                ('ip', models.CharField(max_length=32)),
            ],
        ),
    ]
