# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdlCadre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(blank=True, null=True)),
                ('adlobj_id', models.IntegerField(blank=True, null=True)),
                ('uptodate', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'adl_cadre',
            },
        ),
        migrations.CreateModel(
            name='AdlObj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('local', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=256)),
                ('ext', models.CharField(max_length=16)),
                ('vmsdate', models.DateTimeField(blank=True, null=True)),
                ('svndate', models.DateTimeField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.CharField(blank=True, max_length=256, null=True)),
                ('revision', models.IntegerField(blank=True, null=True)),
                ('sent', models.IntegerField(blank=True, null=True)),
                ('frame', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'adl_obj',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_comment', models.CharField(max_length=1024)),
                ('functional_comment', models.CharField(blank=True, max_length=1024, null=True)),
                ('reference', models.CharField(blank=True, max_length=1024, null=True)),
                ('type_object', models.CharField(blank=True, max_length=256, null=True)),
                ('external_id', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.CharField(max_length=256)),
                ('is_user_doc', models.CharField(blank=True, max_length=1, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('adlobj', models.OneToOneField(db_column='adlobj_id', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='versioning.AdlObj')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='CommentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1024)),
                ('deftype', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comment_type',
            },
        ),
        migrations.CreateModel(
            name='Compilation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(blank=True, null=True)),
                ('maxrev', models.IntegerField(blank=True, null=True)),
                ('adlobj_id', models.IntegerField(blank=True, null=True)),
                ('r_maxrev', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'compilation',
            },
        ),
        migrations.CreateModel(
            name='Dependences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adl_cadre_id', models.IntegerField()),
                ('adl_obj_id', models.IntegerField()),
            ],
            options={
                'db_table': 'dependences',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='Oversee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oversee',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('opt', models.CharField(max_length=256)),
                ('fast', models.IntegerField()),
                ('bin', models.IntegerField()),
                ('listing', models.IntegerField()),
                ('start', models.DateTimeField()),
                ('stop', models.DateTimeField()),
                ('alpha', models.FloatField(blank=True, null=True)),
                ('compiled', models.IntegerField()),
                ('error', models.IntegerField()),
                ('cause', models.CharField(blank=True, max_length=4096, null=True)),
                ('i18n', models.FloatField(blank=True, null=True)),
                ('cuts', models.FloatField(blank=True, null=True)),
                ('gui', models.FloatField(blank=True, null=True)),
                ('klass', models.FloatField(blank=True, null=True)),
                ('ftp_count', models.IntegerField(blank=True, null=True)),
                ('ftp_elapsed', models.FloatField(blank=True, null=True)),
                ('ftp_size', models.FloatField(blank=True, null=True)),
                ('delia_count', models.IntegerField(blank=True, null=True)),
                ('delia_elapsed', models.FloatField(blank=True, null=True)),
                ('delia_size', models.FloatField(blank=True, null=True)),
                ('tree_count', models.IntegerField(blank=True, null=True)),
                ('tree_elapsed', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'statistic',
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024)),
                ('status', models.CharField(max_length=1)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('comment_id', models.IntegerField(blank=True, null=True)),
                ('language_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'translation',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=256)),
                ('role', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_type',
            field=models.ForeignKey(db_column='ctype_id', on_delete=django.db.models.deletion.CASCADE, to='versioning.CommentType'),
        ),
    ]
