# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('versioning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compilation',
            name='adlobj_id',
        ),
        migrations.AddField(
            model_name='compilation',
            name='adlobj',
            field=models.ForeignKey(blank=True, db_column='adlobj_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='versioning.AdlObj'),
        ),
    ]
