# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-21 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versioning', '0002_auto_20160226_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependences',
            name='id',
        ),
        migrations.AlterField(
            model_name='dependences',
            name='adl_obj_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
