# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('data', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
    ]
